# Generated by Django 6.0.3 on 2026-03-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(choices=[('2-wheeler', '2 Wheeler'), ('3-wheeler', '3 Wheeler'), ('4-wheeler', '4 Wheeler')], default='4-wheeler', max_length=20),
        ),
    ]
