# Generated by Django 6.0.3 on 2026-03-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_booking_vehicle_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='created_at',
            new_name='booking_date',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('2-wheeler', '2-Wheeler'), ('3-wheeler', '3-Wheeler'), ('4-wheeler', '4-Wheeler')], default='4-wheeler', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_number',
            field=models.CharField(max_length=10),
        ),
    ]
