# Generated by Django 6.0.3 on 2026-03-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_rename_created_at_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(max_length=20),
        ),
    ]
